services:
  nginx-egress:
    image: adysis/haproxy-side:v1.2.3
    environment:
      SECRET_HEADER_NAME: ${SECRET_HEADER_NAME}
      SECRET_HEADER_VALUE: ${SECRET_HEADER_VALUE}
      READY_PROBE_HOST: ${READY_PROBE_HOST}
    restart: unless-stopped
    network_mode: host
