services:
  nginx-egress:
    image: adysis/haproxy-side:v1.5.0
    environment:
      SECRET_HEADER_NAME: ${SECRET_HEADER_NAME}
      SECRET_HEADER_VALUE: ${SECRET_HEADER_VALUE}
      # READY_PROBE_HOST: ${READY_PROBE_HOST}
    ports:
      - "8709:8709"
    restart: unless-stopped
    network_mode: host
